version: '3.9'
services:
  postgres:
    container_name: shortener-db
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fiber-shortener
    ports:
      - '5432:5432'

  redis:
    container_name: shortener-redis
    image: redis:7.0.4-alpine
    command: redis-server --requirepass secret
    restart: always
    environment:
      - PASSWORD=secret
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  api:
    container_name: shortener-api
    image: sammidev/fiber-shortener:latest
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/fiber-shortener?sslmode=disable
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=secret
    depends_on:
      - postgres
      - redis
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: ['/app/main']

volumes:
  db-data:
    driver: local
  cache:
    driver: local
