// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) error
	GetLinkByLongURL(ctx context.Context, longUrl string) (Link, error)
	GetLinkByShortURL(ctx context.Context, shortUrl string) (Link, error)
}

var _ Querier = (*Queries)(nil)
